name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker Image
      run: docker pull yourusername/yourimage:latest

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i /path/to/your/private-key.pem ec2-user@your-ec2-instance-ip "docker stop your-container-name || true && docker rm your-container-name || true"
        ssh -o StrictHostKeyChecking=no -i /path/to/your/private-key.pem ec2-user@your-ec2-instance-ip "docker run -d --name your-container-name -p 80:80 yourusername/yourimage:latest"
